### ISSUE TITLE
Erro ao trocar de câmera

### ISSUE THREAD

**Issue by wesleyfernandess** [arturaugusto/7seg-ocr#1]
Olá amigo,

quando troco de câmera ele para de funcionar, no console tem erro ao abrir o vídeo, quando abre a primeira vez (primeira câmera funciona legal)

![image](https://user-images.githubusercontent.com/44230033/163065194-b2e4bc28-00a7-43cd-b4ad-3fe55179a034.png)

**Comment by arturaugusto** [comment]
Não consegui reproduzir o problema. Consegui usar com duas câmeras.

Uma alternativa é alterar a câmera padrão no navegador. No Chrome basta clicar no ícone da câmera na barra de endereço, depois gerenciar e alterar na lista.

**Comment by wesleyfernandess** [comment]
Eu tenho um grupo só com a galera que faz transmissão esportiva no BR e a galera fala muito sobre algo para capturar os dados e enviar para o software de transmissão ao vivo ou até via json ou até txt. Vi seu trampo e achei muito legal e queria testar, mas pra isso usar uma câmera virtual para capturar a tela o painel, enviar para sua aplicação e devolver para usar nos GCs de alguma forma.
